ol.proj.proj4.register(proj4);
//ol.proj.get("EPSG:4326").setExtent([122.691938, 7.335628, 126.357760, 9.308161]);
var wms_layers = [];


        var lyr_GoogleEarth_0 = new ol.layer.Tile({
            'title': 'Google Earth',
            'opacity': 1.000000,
            
            
            source: new ol.source.XYZ({
            attributions: ' ',
                url: 'http://mt0.google.com/vt/lyrs=s&hl=en&x={x}&y={y}&z={z}'
            })
        });

        var lyr_OpenStreetMap_1 = new ol.layer.Tile({
            'title': 'Open Street Map',
            'opacity': 1.000000,
            
            
            source: new ol.source.XYZ({
            attributions: ' ',
                url: 'https://tile.openstreetmap.org/{z}/{x}/{y}.png'
            })
        });
var format_4PrivateWarehouseNotActive_2 = new ol.format.GeoJSON();
var features_4PrivateWarehouseNotActive_2 = format_4PrivateWarehouseNotActive_2.readFeatures(json_4PrivateWarehouseNotActive_2, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:4326'});
var jsonSource_4PrivateWarehouseNotActive_2 = new ol.source.Vector({
    attributions: ' ',
});
jsonSource_4PrivateWarehouseNotActive_2.addFeatures(features_4PrivateWarehouseNotActive_2);
var lyr_4PrivateWarehouseNotActive_2 = new ol.layer.Vector({
                declutter: false,
                source:jsonSource_4PrivateWarehouseNotActive_2, 
                style: style_4PrivateWarehouseNotActive_2,
                popuplayertitle: '4 Private Warehouse (Not Active)',
                interactive: true,
                title: '<img src="styles/legend/4PrivateWarehouseNotActive_2.png" /> 4 Private Warehouse (Not Active)'
            });
var format_9GovernmentWarehouseNotActive_3 = new ol.format.GeoJSON();
var features_9GovernmentWarehouseNotActive_3 = format_9GovernmentWarehouseNotActive_3.readFeatures(json_9GovernmentWarehouseNotActive_3, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:4326'});
var jsonSource_9GovernmentWarehouseNotActive_3 = new ol.source.Vector({
    attributions: ' ',
});
jsonSource_9GovernmentWarehouseNotActive_3.addFeatures(features_9GovernmentWarehouseNotActive_3);
var lyr_9GovernmentWarehouseNotActive_3 = new ol.layer.Vector({
                declutter: false,
                source:jsonSource_9GovernmentWarehouseNotActive_3, 
                style: style_9GovernmentWarehouseNotActive_3,
                popuplayertitle: '9 Government Warehouse (Not Active)',
                interactive: true,
                title: '<img src="styles/legend/9GovernmentWarehouseNotActive_3.png" /> 9 Government Warehouse (Not Active)'
            });
var format_154PrivateWarehouseActive_4 = new ol.format.GeoJSON();
var features_154PrivateWarehouseActive_4 = format_154PrivateWarehouseActive_4.readFeatures(json_154PrivateWarehouseActive_4, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:4326'});
var jsonSource_154PrivateWarehouseActive_4 = new ol.source.Vector({
    attributions: ' ',
});
jsonSource_154PrivateWarehouseActive_4.addFeatures(features_154PrivateWarehouseActive_4);
var lyr_154PrivateWarehouseActive_4 = new ol.layer.Vector({
                declutter: false,
                source:jsonSource_154PrivateWarehouseActive_4, 
                style: style_154PrivateWarehouseActive_4,
                popuplayertitle: '154 Private Warehouse (Active)',
                interactive: true,
                title: '<img src="styles/legend/154PrivateWarehouseActive_4.png" /> 154 Private Warehouse (Active)'
            });
var format_124GovernmentWarehouseActive_5 = new ol.format.GeoJSON();
var features_124GovernmentWarehouseActive_5 = format_124GovernmentWarehouseActive_5.readFeatures(json_124GovernmentWarehouseActive_5, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:4326'});
var jsonSource_124GovernmentWarehouseActive_5 = new ol.source.Vector({
    attributions: ' ',
});
jsonSource_124GovernmentWarehouseActive_5.addFeatures(features_124GovernmentWarehouseActive_5);
var lyr_124GovernmentWarehouseActive_5 = new ol.layer.Vector({
                declutter: false,
                source:jsonSource_124GovernmentWarehouseActive_5, 
                style: style_124GovernmentWarehouseActive_5,
                popuplayertitle: '124 Government Warehouse (Active)',
                interactive: true,
                title: '<img src="styles/legend/124GovernmentWarehouseActive_5.png" /> 124 Government Warehouse (Active)'
            });
var format_Region10MunicipalandCityBoundaries_6 = new ol.format.GeoJSON();
var features_Region10MunicipalandCityBoundaries_6 = format_Region10MunicipalandCityBoundaries_6.readFeatures(json_Region10MunicipalandCityBoundaries_6, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:4326'});
var jsonSource_Region10MunicipalandCityBoundaries_6 = new ol.source.Vector({
    attributions: ' ',
});
jsonSource_Region10MunicipalandCityBoundaries_6.addFeatures(features_Region10MunicipalandCityBoundaries_6);
var lyr_Region10MunicipalandCityBoundaries_6 = new ol.layer.Vector({
                declutter: false,
                source:jsonSource_Region10MunicipalandCityBoundaries_6, 
                style: style_Region10MunicipalandCityBoundaries_6,
                popuplayertitle: 'Region 10 Municipal and City Boundaries',
                interactive: true,
                title: '<img src="styles/legend/Region10MunicipalandCityBoundaries_6.png" /> Region 10 Municipal and City Boundaries'
            });

lyr_GoogleEarth_0.setVisible(true);lyr_OpenStreetMap_1.setVisible(true);lyr_4PrivateWarehouseNotActive_2.setVisible(true);lyr_9GovernmentWarehouseNotActive_3.setVisible(true);lyr_154PrivateWarehouseActive_4.setVisible(true);lyr_124GovernmentWarehouseActive_5.setVisible(true);lyr_Region10MunicipalandCityBoundaries_6.setVisible(true);
var layersList = [lyr_GoogleEarth_0,lyr_OpenStreetMap_1,lyr_4PrivateWarehouseNotActive_2,lyr_9GovernmentWarehouseNotActive_3,lyr_154PrivateWarehouseActive_4,lyr_124GovernmentWarehouseActive_5,lyr_Region10MunicipalandCityBoundaries_6];
lyr_4PrivateWarehouseNotActive_2.set('fieldAliases', {'Timestamp': 'Timestamp', 'Email address': 'Email address', 'NAME OF WAREHOUSE': 'NAME OF WAREHOUSE', 'TYPE': 'TYPE', 'BARANGAY': 'BARANGAY', 'MUNICIPALITY/CITY': 'MUNICIPALITY/CITY', 'DISTRICT': 'DISTRICT', 'DATE OF VISIT': 'DATE OF VISIT', 'OWNERSHIP STATUS': 'OWNERSHIP STATUS', 'OWNER\'S NAME': 'OWNER\'S NAME', 'OWNER\'S CONTACT NUMBER (if available)': 'OWNER\'S CONTACT NUMBER (if available)', 'WAREHOUSE MAN NAME (if any)': 'WAREHOUSE MAN NAME (if any)', 'WAREHOUSE MAN CONTACT NUMBER (if available)': 'WAREHOUSE MAN CONTACT NUMBER (if available)', 'WAREHOUSE CAPACITY (in MT or sacks)': 'WAREHOUSE CAPACITY (in MT or sacks)', 'MAIN COMMODITY STORED (Rice, Corn, Cacao, Fertilizer, General Goods, etc.)': 'MAIN COMMODITY STORED (Rice, Corn, Cacao, Fertilizer, General Goods, etc.)', 'STATUS': 'STATUS', 'YEAR BUILT (if known)': 'YEAR BUILT (if known)', 'WAREHOUSE DIMENSIONS (meters)': 'WAREHOUSE DIMENSIONS (meters)', 'HEIGHT OF STRUCTURE (FFL to Beam) meters': 'HEIGHT OF STRUCTURE (FFL to Beam) meters', 'EXISTING FIREFIGHTING EQUIPMENT': 'EXISTING FIREFIGHTING EQUIPMENT', 'SECURITY': 'SECURITY', 'Latitude': 'Latitude', 'Longitude': 'Longitude', 'GEOTAGGED PHOTO TAKEN': 'GEOTAGGED PHOTO TAKEN', 'GEOTAGGED PHOTO': 'GEOTAGGED PHOTO', 'REMARKS/NOTES': 'REMARKS/NOTES', 'NAME OF ENCODER': 'NAME OF ENCODER', 'PROVINCE': 'PROVINCE', });
lyr_9GovernmentWarehouseNotActive_3.set('fieldAliases', {'Timestamp': 'Timestamp', 'Email address': 'Email address', 'NAME OF WAREHOUSE': 'NAME OF WAREHOUSE', 'TYPE': 'TYPE', 'BARANGAY': 'BARANGAY', 'MUNICIPALITY/CITY': 'MUNICIPALITY/CITY', 'DISTRICT': 'DISTRICT', 'DATE OF VISIT': 'DATE OF VISIT', 'OWNERSHIP STATUS': 'OWNERSHIP STATUS', 'OWNER\'S NAME': 'OWNER\'S NAME', 'OWNER\'S CONTACT NUMBER (if available)': 'OWNER\'S CONTACT NUMBER (if available)', 'WAREHOUSE MAN NAME (if any)': 'WAREHOUSE MAN NAME (if any)', 'WAREHOUSE MAN CONTACT NUMBER (if available)': 'WAREHOUSE MAN CONTACT NUMBER (if available)', 'WAREHOUSE CAPACITY (in MT or sacks)': 'WAREHOUSE CAPACITY (in MT or sacks)', 'MAIN COMMODITY STORED (Rice, Corn, Cacao, Fertilizer, General Goods, etc.)': 'MAIN COMMODITY STORED (Rice, Corn, Cacao, Fertilizer, General Goods, etc.)', 'STATUS': 'STATUS', 'YEAR BUILT (if known)': 'YEAR BUILT (if known)', 'WAREHOUSE DIMENSIONS (meters)': 'WAREHOUSE DIMENSIONS (meters)', 'HEIGHT OF STRUCTURE (FFL to Beam) meters': 'HEIGHT OF STRUCTURE (FFL to Beam) meters', 'EXISTING FIREFIGHTING EQUIPMENT': 'EXISTING FIREFIGHTING EQUIPMENT', 'SECURITY': 'SECURITY', 'Latitude': 'Latitude', 'Longitude': 'Longitude', 'GEOTAGGED PHOTO TAKEN': 'GEOTAGGED PHOTO TAKEN', 'GEOTAGGED PHOTO': 'GEOTAGGED PHOTO', 'REMARKS/NOTES': 'REMARKS/NOTES', 'NAME OF ENCODER': 'NAME OF ENCODER', 'PROVINCE': 'PROVINCE', });
lyr_154PrivateWarehouseActive_4.set('fieldAliases', {'Timestamp': 'Timestamp', 'Email address': 'Email address', 'NAME OF WAREHOUSE': 'NAME OF WAREHOUSE', 'TYPE': 'TYPE', 'BARANGAY': 'BARANGAY', 'MUNICIPALITY/CITY': 'MUNICIPALITY/CITY', 'DISTRICT': 'DISTRICT', 'DATE OF VISIT': 'DATE OF VISIT', 'OWNERSHIP STATUS': 'OWNERSHIP STATUS', 'OWNER\'S NAME': 'OWNER\'S NAME', 'OWNER\'S CONTACT NUMBER (if available)': 'OWNER\'S CONTACT NUMBER (if available)', 'WAREHOUSE MAN NAME (if any)': 'WAREHOUSE MAN NAME (if any)', 'WAREHOUSE MAN CONTACT NUMBER (if available)': 'WAREHOUSE MAN CONTACT NUMBER (if available)', 'WAREHOUSE CAPACITY (in MT or sacks)': 'WAREHOUSE CAPACITY (in MT or sacks)', 'MAIN COMMODITY STORED (Rice, Corn, Cacao, Fertilizer, General Goods, etc.)': 'MAIN COMMODITY STORED (Rice, Corn, Cacao, Fertilizer, General Goods, etc.)', 'STATUS': 'STATUS', 'YEAR BUILT (if known)': 'YEAR BUILT (if known)', 'WAREHOUSE DIMENSIONS (meters)': 'WAREHOUSE DIMENSIONS (meters)', 'HEIGHT OF STRUCTURE (FFL to Beam) meters': 'HEIGHT OF STRUCTURE (FFL to Beam) meters', 'EXISTING FIREFIGHTING EQUIPMENT': 'EXISTING FIREFIGHTING EQUIPMENT', 'SECURITY': 'SECURITY', 'Latitude': 'Latitude', 'Longitude': 'Longitude', 'GEOTAGGED PHOTO TAKEN': 'GEOTAGGED PHOTO TAKEN', 'GEOTAGGED PHOTO': 'GEOTAGGED PHOTO', 'REMARKS/NOTES': 'REMARKS/NOTES', 'NAME OF ENCODER': 'NAME OF ENCODER', 'PROVINCE': 'PROVINCE', });
lyr_124GovernmentWarehouseActive_5.set('fieldAliases', {'Timestamp': 'Timestamp', 'Email address': 'Email address', 'NAME OF WAREHOUSE': 'NAME OF WAREHOUSE', 'TYPE': 'TYPE', 'BARANGAY': 'BARANGAY', 'MUNICIPALITY/CITY': 'MUNICIPALITY/CITY', 'DISTRICT': 'DISTRICT', 'DATE OF VISIT': 'DATE OF VISIT', 'OWNERSHIP STATUS': 'OWNERSHIP STATUS', 'OWNER\'S NAME': 'OWNER\'S NAME', 'OWNER\'S CONTACT NUMBER (if available)': 'OWNER\'S CONTACT NUMBER (if available)', 'WAREHOUSE MAN NAME (if any)': 'WAREHOUSE MAN NAME (if any)', 'WAREHOUSE MAN CONTACT NUMBER (if available)': 'WAREHOUSE MAN CONTACT NUMBER (if available)', 'WAREHOUSE CAPACITY (in MT or sacks)': 'WAREHOUSE CAPACITY (in MT or sacks)', 'MAIN COMMODITY STORED (Rice, Corn, Cacao, Fertilizer, General Goods, etc.)': 'MAIN COMMODITY STORED (Rice, Corn, Cacao, Fertilizer, General Goods, etc.)', 'STATUS': 'STATUS', 'YEAR BUILT (if known)': 'YEAR BUILT (if known)', 'WAREHOUSE DIMENSIONS (meters)': 'WAREHOUSE DIMENSIONS (meters)', 'HEIGHT OF STRUCTURE (FFL to Beam) meters': 'HEIGHT OF STRUCTURE (FFL to Beam) meters', 'EXISTING FIREFIGHTING EQUIPMENT': 'EXISTING FIREFIGHTING EQUIPMENT', 'SECURITY': 'SECURITY', 'Latitude': 'Latitude', 'Longitude': 'Longitude', 'GEOTAGGED PHOTO TAKEN': 'GEOTAGGED PHOTO TAKEN', 'GEOTAGGED PHOTO': 'GEOTAGGED PHOTO', 'REMARKS/NOTES': 'REMARKS/NOTES', 'NAME OF ENCODER': 'NAME OF ENCODER', 'PROVINCE': 'PROVINCE', });
lyr_Region10MunicipalandCityBoundaries_6.set('fieldAliases', {'Name': 'Name', 'description': 'description', 'timestamp': 'timestamp', 'begin': 'begin', 'end': 'end', 'altitudeMode': 'altitudeMode', 'tessellate': 'tessellate', 'extrude': 'extrude', 'visibility': 'visibility', 'drawOrder': 'drawOrder', 'icon': 'icon', 'admityes': 'admityes', 'admitno': 'admitno', 'admitfv': 'admitfv', 'recover': 'recover', 'died': 'died', 'remvlfv': 'remvlfv', 'female': 'female', 'male': 'male', 'sexfv': 'sexfv', 'ag0004': 'ag0004', 'ag0509': 'ag0509', 'ag1014': 'ag1014', 'ag1519': 'ag1519', 'ag2024': 'ag2024', 'ag2529': 'ag2529', 'ag3034': 'ag3034', 'ag3539': 'ag3539', 'ag4044': 'ag4044', 'ag4549': 'ag4549', 'ag5054': 'ag5054', 'ag5559': 'ag5559', 'ag6064': 'ag6064', 'ag6569': 'ag6569', 'ag7074': 'ag7074', 'ag7579': 'ag7579', 'ag8000': 'ag8000', 'agfv': 'agfv', 'totcases': 'totcases', 'region': 'region', 'prov': 'prov', 'psgc': 'psgc', 'mun': 'mun', });
lyr_4PrivateWarehouseNotActive_2.set('fieldImages', {'Timestamp': 'TextEdit', 'Email address': 'TextEdit', 'NAME OF WAREHOUSE': 'TextEdit', 'TYPE': 'TextEdit', 'BARANGAY': 'TextEdit', 'MUNICIPALITY/CITY': 'TextEdit', 'DISTRICT': 'TextEdit', 'DATE OF VISIT': 'TextEdit', 'OWNERSHIP STATUS': 'TextEdit', 'OWNER\'S NAME': 'TextEdit', 'OWNER\'S CONTACT NUMBER (if available)': 'TextEdit', 'WAREHOUSE MAN NAME (if any)': 'TextEdit', 'WAREHOUSE MAN CONTACT NUMBER (if available)': 'TextEdit', 'WAREHOUSE CAPACITY (in MT or sacks)': 'TextEdit', 'MAIN COMMODITY STORED (Rice, Corn, Cacao, Fertilizer, General Goods, etc.)': 'TextEdit', 'STATUS': 'TextEdit', 'YEAR BUILT (if known)': 'TextEdit', 'WAREHOUSE DIMENSIONS (meters)': 'TextEdit', 'HEIGHT OF STRUCTURE (FFL to Beam) meters': 'TextEdit', 'EXISTING FIREFIGHTING EQUIPMENT': 'TextEdit', 'SECURITY': 'TextEdit', 'Latitude': 'TextEdit', 'Longitude': 'TextEdit', 'GEOTAGGED PHOTO TAKEN': 'CheckBox', 'GEOTAGGED PHOTO': 'TextEdit', 'REMARKS/NOTES': 'TextEdit', 'NAME OF ENCODER': 'TextEdit', 'PROVINCE': 'TextEdit', });
lyr_9GovernmentWarehouseNotActive_3.set('fieldImages', {'Timestamp': 'TextEdit', 'Email address': 'TextEdit', 'NAME OF WAREHOUSE': 'TextEdit', 'TYPE': 'TextEdit', 'BARANGAY': 'TextEdit', 'MUNICIPALITY/CITY': 'TextEdit', 'DISTRICT': 'TextEdit', 'DATE OF VISIT': 'TextEdit', 'OWNERSHIP STATUS': 'TextEdit', 'OWNER\'S NAME': 'TextEdit', 'OWNER\'S CONTACT NUMBER (if available)': 'TextEdit', 'WAREHOUSE MAN NAME (if any)': 'TextEdit', 'WAREHOUSE MAN CONTACT NUMBER (if available)': 'TextEdit', 'WAREHOUSE CAPACITY (in MT or sacks)': 'TextEdit', 'MAIN COMMODITY STORED (Rice, Corn, Cacao, Fertilizer, General Goods, etc.)': 'TextEdit', 'STATUS': 'TextEdit', 'YEAR BUILT (if known)': 'TextEdit', 'WAREHOUSE DIMENSIONS (meters)': 'TextEdit', 'HEIGHT OF STRUCTURE (FFL to Beam) meters': 'TextEdit', 'EXISTING FIREFIGHTING EQUIPMENT': 'TextEdit', 'SECURITY': 'TextEdit', 'Latitude': 'TextEdit', 'Longitude': 'TextEdit', 'GEOTAGGED PHOTO TAKEN': 'CheckBox', 'GEOTAGGED PHOTO': 'TextEdit', 'REMARKS/NOTES': 'TextEdit', 'NAME OF ENCODER': 'TextEdit', 'PROVINCE': 'TextEdit', });
lyr_154PrivateWarehouseActive_4.set('fieldImages', {'Timestamp': 'TextEdit', 'Email address': 'TextEdit', 'NAME OF WAREHOUSE': 'TextEdit', 'TYPE': 'TextEdit', 'BARANGAY': 'TextEdit', 'MUNICIPALITY/CITY': 'TextEdit', 'DISTRICT': 'TextEdit', 'DATE OF VISIT': 'TextEdit', 'OWNERSHIP STATUS': 'TextEdit', 'OWNER\'S NAME': 'TextEdit', 'OWNER\'S CONTACT NUMBER (if available)': 'TextEdit', 'WAREHOUSE MAN NAME (if any)': 'TextEdit', 'WAREHOUSE MAN CONTACT NUMBER (if available)': 'TextEdit', 'WAREHOUSE CAPACITY (in MT or sacks)': 'TextEdit', 'MAIN COMMODITY STORED (Rice, Corn, Cacao, Fertilizer, General Goods, etc.)': 'TextEdit', 'STATUS': 'TextEdit', 'YEAR BUILT (if known)': 'TextEdit', 'WAREHOUSE DIMENSIONS (meters)': 'TextEdit', 'HEIGHT OF STRUCTURE (FFL to Beam) meters': 'TextEdit', 'EXISTING FIREFIGHTING EQUIPMENT': 'TextEdit', 'SECURITY': 'TextEdit', 'Latitude': 'TextEdit', 'Longitude': 'TextEdit', 'GEOTAGGED PHOTO TAKEN': 'TextEdit', 'GEOTAGGED PHOTO': 'TextEdit', 'REMARKS/NOTES': 'TextEdit', 'NAME OF ENCODER': 'TextEdit', 'PROVINCE': 'TextEdit', });
lyr_124GovernmentWarehouseActive_5.set('fieldImages', {'Timestamp': 'TextEdit', 'Email address': 'TextEdit', 'NAME OF WAREHOUSE': 'TextEdit', 'TYPE': 'TextEdit', 'BARANGAY': 'TextEdit', 'MUNICIPALITY/CITY': 'TextEdit', 'DISTRICT': 'TextEdit', 'DATE OF VISIT': 'TextEdit', 'OWNERSHIP STATUS': 'TextEdit', 'OWNER\'S NAME': 'TextEdit', 'OWNER\'S CONTACT NUMBER (if available)': 'TextEdit', 'WAREHOUSE MAN NAME (if any)': 'TextEdit', 'WAREHOUSE MAN CONTACT NUMBER (if available)': 'TextEdit', 'WAREHOUSE CAPACITY (in MT or sacks)': 'TextEdit', 'MAIN COMMODITY STORED (Rice, Corn, Cacao, Fertilizer, General Goods, etc.)': 'TextEdit', 'STATUS': 'TextEdit', 'YEAR BUILT (if known)': 'TextEdit', 'WAREHOUSE DIMENSIONS (meters)': 'TextEdit', 'HEIGHT OF STRUCTURE (FFL to Beam) meters': 'TextEdit', 'EXISTING FIREFIGHTING EQUIPMENT': 'TextEdit', 'SECURITY': 'TextEdit', 'Latitude': 'TextEdit', 'Longitude': 'TextEdit', 'GEOTAGGED PHOTO TAKEN': 'TextEdit', 'GEOTAGGED PHOTO': 'TextEdit', 'REMARKS/NOTES': 'TextEdit', 'NAME OF ENCODER': 'TextEdit', 'PROVINCE': 'TextEdit', });
lyr_Region10MunicipalandCityBoundaries_6.set('fieldImages', {'Name': 'TextEdit', 'description': 'TextEdit', 'timestamp': 'DateTime', 'begin': 'DateTime', 'end': 'DateTime', 'altitudeMode': 'TextEdit', 'tessellate': 'Range', 'extrude': 'Range', 'visibility': 'Range', 'drawOrder': 'Range', 'icon': 'TextEdit', 'admityes': 'TextEdit', 'admitno': 'TextEdit', 'admitfv': 'TextEdit', 'recover': 'TextEdit', 'died': 'TextEdit', 'remvlfv': 'TextEdit', 'female': 'TextEdit', 'male': 'TextEdit', 'sexfv': 'TextEdit', 'ag0004': 'TextEdit', 'ag0509': 'TextEdit', 'ag1014': 'TextEdit', 'ag1519': 'TextEdit', 'ag2024': 'TextEdit', 'ag2529': 'TextEdit', 'ag3034': 'TextEdit', 'ag3539': 'TextEdit', 'ag4044': 'TextEdit', 'ag4549': 'TextEdit', 'ag5054': 'TextEdit', 'ag5559': 'TextEdit', 'ag6064': 'TextEdit', 'ag6569': 'TextEdit', 'ag7074': 'TextEdit', 'ag7579': 'TextEdit', 'ag8000': 'TextEdit', 'agfv': 'TextEdit', 'totcases': 'TextEdit', 'region': 'TextEdit', 'prov': 'TextEdit', 'psgc': 'TextEdit', 'mun': 'TextEdit', });
lyr_4PrivateWarehouseNotActive_2.set('fieldLabels', {'Timestamp': 'inline label - visible with data', 'Email address': 'inline label - visible with data', 'NAME OF WAREHOUSE': 'inline label - visible with data', 'TYPE': 'inline label - visible with data', 'BARANGAY': 'inline label - visible with data', 'MUNICIPALITY/CITY': 'inline label - visible with data', 'DISTRICT': 'inline label - visible with data', 'DATE OF VISIT': 'inline label - visible with data', 'OWNERSHIP STATUS': 'inline label - visible with data', 'OWNER\'S NAME': 'inline label - visible with data', 'OWNER\'S CONTACT NUMBER (if available)': 'inline label - visible with data', 'WAREHOUSE MAN NAME (if any)': 'inline label - visible with data', 'WAREHOUSE MAN CONTACT NUMBER (if available)': 'inline label - visible with data', 'WAREHOUSE CAPACITY (in MT or sacks)': 'inline label - visible with data', 'MAIN COMMODITY STORED (Rice, Corn, Cacao, Fertilizer, General Goods, etc.)': 'inline label - visible with data', 'STATUS': 'inline label - visible with data', 'YEAR BUILT (if known)': 'inline label - visible with data', 'WAREHOUSE DIMENSIONS (meters)': 'inline label - visible with data', 'HEIGHT OF STRUCTURE (FFL to Beam) meters': 'inline label - visible with data', 'EXISTING FIREFIGHTING EQUIPMENT': 'inline label - visible with data', 'SECURITY': 'inline label - visible with data', 'Latitude': 'inline label - visible with data', 'Longitude': 'inline label - visible with data', 'GEOTAGGED PHOTO TAKEN': 'inline label - visible with data', 'GEOTAGGED PHOTO': 'inline label - visible with data', 'REMARKS/NOTES': 'inline label - visible with data', 'NAME OF ENCODER': 'inline label - visible with data', 'PROVINCE': 'inline label - visible with data', });
lyr_9GovernmentWarehouseNotActive_3.set('fieldLabels', {'Timestamp': 'inline label - visible with data', 'Email address': 'inline label - visible with data', 'NAME OF WAREHOUSE': 'inline label - visible with data', 'TYPE': 'inline label - visible with data', 'BARANGAY': 'inline label - visible with data', 'MUNICIPALITY/CITY': 'inline label - visible with data', 'DISTRICT': 'inline label - visible with data', 'DATE OF VISIT': 'inline label - visible with data', 'OWNERSHIP STATUS': 'inline label - visible with data', 'OWNER\'S NAME': 'inline label - visible with data', 'OWNER\'S CONTACT NUMBER (if available)': 'inline label - visible with data', 'WAREHOUSE MAN NAME (if any)': 'inline label - visible with data', 'WAREHOUSE MAN CONTACT NUMBER (if available)': 'inline label - visible with data', 'WAREHOUSE CAPACITY (in MT or sacks)': 'inline label - visible with data', 'MAIN COMMODITY STORED (Rice, Corn, Cacao, Fertilizer, General Goods, etc.)': 'inline label - visible with data', 'STATUS': 'inline label - visible with data', 'YEAR BUILT (if known)': 'inline label - visible with data', 'WAREHOUSE DIMENSIONS (meters)': 'inline label - visible with data', 'HEIGHT OF STRUCTURE (FFL to Beam) meters': 'inline label - visible with data', 'EXISTING FIREFIGHTING EQUIPMENT': 'inline label - visible with data', 'SECURITY': 'inline label - visible with data', 'Latitude': 'inline label - visible with data', 'Longitude': 'inline label - visible with data', 'GEOTAGGED PHOTO TAKEN': 'inline label - visible with data', 'GEOTAGGED PHOTO': 'inline label - visible with data', 'REMARKS/NOTES': 'inline label - visible with data', 'NAME OF ENCODER': 'inline label - visible with data', 'PROVINCE': 'inline label - visible with data', });
lyr_154PrivateWarehouseActive_4.set('fieldLabels', {'Timestamp': 'inline label - visible with data', 'Email address': 'inline label - visible with data', 'NAME OF WAREHOUSE': 'inline label - visible with data', 'TYPE': 'inline label - visible with data', 'BARANGAY': 'inline label - visible with data', 'MUNICIPALITY/CITY': 'inline label - visible with data', 'DISTRICT': 'inline label - visible with data', 'DATE OF VISIT': 'inline label - visible with data', 'OWNERSHIP STATUS': 'inline label - visible with data', 'OWNER\'S NAME': 'inline label - visible with data', 'OWNER\'S CONTACT NUMBER (if available)': 'inline label - visible with data', 'WAREHOUSE MAN NAME (if any)': 'inline label - visible with data', 'WAREHOUSE MAN CONTACT NUMBER (if available)': 'inline label - visible with data', 'WAREHOUSE CAPACITY (in MT or sacks)': 'inline label - visible with data', 'MAIN COMMODITY STORED (Rice, Corn, Cacao, Fertilizer, General Goods, etc.)': 'inline label - visible with data', 'STATUS': 'inline label - visible with data', 'YEAR BUILT (if known)': 'inline label - visible with data', 'WAREHOUSE DIMENSIONS (meters)': 'inline label - visible with data', 'HEIGHT OF STRUCTURE (FFL to Beam) meters': 'inline label - visible with data', 'EXISTING FIREFIGHTING EQUIPMENT': 'inline label - visible with data', 'SECURITY': 'inline label - visible with data', 'Latitude': 'inline label - visible with data', 'Longitude': 'inline label - visible with data', 'GEOTAGGED PHOTO TAKEN': 'inline label - visible with data', 'GEOTAGGED PHOTO': 'inline label - visible with data', 'REMARKS/NOTES': 'inline label - visible with data', 'NAME OF ENCODER': 'inline label - visible with data', 'PROVINCE': 'inline label - visible with data', });
lyr_124GovernmentWarehouseActive_5.set('fieldLabels', {'Timestamp': 'inline label - visible with data', 'Email address': 'inline label - visible with data', 'NAME OF WAREHOUSE': 'inline label - visible with data', 'TYPE': 'inline label - visible with data', 'BARANGAY': 'inline label - visible with data', 'MUNICIPALITY/CITY': 'inline label - visible with data', 'DISTRICT': 'inline label - visible with data', 'DATE OF VISIT': 'inline label - visible with data', 'OWNERSHIP STATUS': 'inline label - visible with data', 'OWNER\'S NAME': 'inline label - visible with data', 'OWNER\'S CONTACT NUMBER (if available)': 'inline label - visible with data', 'WAREHOUSE MAN NAME (if any)': 'inline label - visible with data', 'WAREHOUSE MAN CONTACT NUMBER (if available)': 'inline label - visible with data', 'WAREHOUSE CAPACITY (in MT or sacks)': 'inline label - visible with data', 'MAIN COMMODITY STORED (Rice, Corn, Cacao, Fertilizer, General Goods, etc.)': 'inline label - visible with data', 'STATUS': 'inline label - visible with data', 'YEAR BUILT (if known)': 'inline label - visible with data', 'WAREHOUSE DIMENSIONS (meters)': 'inline label - visible with data', 'HEIGHT OF STRUCTURE (FFL to Beam) meters': 'inline label - visible with data', 'EXISTING FIREFIGHTING EQUIPMENT': 'inline label - visible with data', 'SECURITY': 'inline label - visible with data', 'Latitude': 'inline label - visible with data', 'Longitude': 'inline label - visible with data', 'GEOTAGGED PHOTO TAKEN': 'inline label - visible with data', 'GEOTAGGED PHOTO': 'inline label - visible with data', 'REMARKS/NOTES': 'inline label - visible with data', 'NAME OF ENCODER': 'inline label - visible with data', 'PROVINCE': 'inline label - visible with data', });
lyr_Region10MunicipalandCityBoundaries_6.set('fieldLabels', {'Name': 'inline label - visible with data', 'description': 'inline label - visible with data', 'timestamp': 'inline label - visible with data', 'begin': 'inline label - visible with data', 'end': 'inline label - visible with data', 'altitudeMode': 'inline label - visible with data', 'tessellate': 'inline label - visible with data', 'extrude': 'inline label - visible with data', 'visibility': 'inline label - visible with data', 'drawOrder': 'inline label - visible with data', 'icon': 'inline label - visible with data', 'admityes': 'inline label - visible with data', 'admitno': 'inline label - visible with data', 'admitfv': 'inline label - visible with data', 'recover': 'inline label - visible with data', 'died': 'inline label - visible with data', 'remvlfv': 'inline label - visible with data', 'female': 'inline label - visible with data', 'male': 'inline label - visible with data', 'sexfv': 'inline label - visible with data', 'ag0004': 'inline label - visible with data', 'ag0509': 'inline label - visible with data', 'ag1014': 'inline label - visible with data', 'ag1519': 'inline label - visible with data', 'ag2024': 'inline label - visible with data', 'ag2529': 'inline label - visible with data', 'ag3034': 'inline label - visible with data', 'ag3539': 'inline label - visible with data', 'ag4044': 'inline label - visible with data', 'ag4549': 'inline label - visible with data', 'ag5054': 'inline label - visible with data', 'ag5559': 'inline label - visible with data', 'ag6064': 'inline label - visible with data', 'ag6569': 'inline label - visible with data', 'ag7074': 'inline label - visible with data', 'ag7579': 'inline label - visible with data', 'ag8000': 'inline label - visible with data', 'agfv': 'inline label - visible with data', 'totcases': 'inline label - visible with data', 'region': 'inline label - visible with data', 'prov': 'inline label - visible with data', 'psgc': 'inline label - visible with data', 'mun': 'inline label - visible with data', });
lyr_Region10MunicipalandCityBoundaries_6.on('precompose', function(evt) {
    evt.context.globalCompositeOperation = 'normal';
});